development:
  contact_form_email: s.lamb@hull.ac.uk
 
  #catalog address/port used for Z39.50 interface for holdings
  catalog_server_address: libsys.lib.hull.ac.uk
  catalog_server_port: 210

test:
  contact_form_email: s.lamb@hull.ac.uk

  #catalog address/port used for Z39.50 interface for holdings
  catalog_server_address: libsys.lib.hull.ac.uk
  catalog_server_port: 210

production:
  contact_form_email: s.lamb@hull.ac.uk

  #catalog address/port used for Z39.50 interface for holdings
  catalog_server_address: libsys.lib.hull.ac.uk
  catalog_server_port: 210
