development:
  contact_form_email: r.j.garbutt@hull.ac.uk
  contact_form_bcc:
    - r.j.garbutt@hull.ac.uk

  #catalog address/port used for Z39.50 interface for holdings
  catalogue_server_address: libsys.lib.hull.ac.uk
  catalogue_server_port: 210

  #Z39.50 connection pool configurations
  #5 appears to be an optimal poolsize
  z39_connection_pool_size: 5
  z39_connection_timeout: 5
  
  #Library Catalogue OPAC address
  catalogue_opac_address: library.hull.ac.uk

  #Library Inter-library loan url
  inter_library_loan_address: http://www2.hull.ac.uk/lli/library-services/books/interlibrary-loan.aspx

  # Intersite transfer url
  intersite_transfer_url: http://www2.hull.ac.uk/lli/library-services/books/intersite.aspx

  #syndetics services for book covers and table of contents
  syndetics_client_code: dev

  # Used for building the link structure for the York 
  york_link_desc: 'This item in University of York Library'
  york_link_url: 'http://yorsearch.york.ac.uk/primo_library/libweb/action/dlSearch.do?institution=44YORK&vid=44YORK&query=any,contains,'

  # twitter widget data_id
  twitter_widget_data_id: 

  #configurations for addthis tool - See http://support.addthis.com/customer/portal/articles/381244-destinations-services
  addthis_services_compact: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket'
  addthis_services_expanded: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket,favorites'
  addthis_services_exclude: 'gmail,email'

  #Do not retrieve holdings for these formats
  holdings:
    ignore:
      - 'E-Book'
      - 'E-Journal'
      - 'Electronic resource'
      - 'Unknown'

  #status from holding records
  record_status:
    available:
      - 'ask at dept'
      - 'ask at hdc'   
      - 'available'
      - 'beingprocessed'
      - 'binding office'
      - 'donation'
      - 'due'
      - 'in repair'
      - 'in transit'
      - 'just catalogued'
      - 'on holdshelf'
      - 'requested'
      - 'returned today'
      - 'to collect'  
    not_available:
      - 'at bindery'
      - 'billed'
      - 'clms retd'
      - 'damaged copy'
      - 'disk missing'
      - 'intersite'
      - 'librar/office'
      - 'lib use only'
      - 'lost and paid'
      - 'lost in lib'
      - 'lost o/o/p'
      - 'missing'
      - 'not available'
      - 'on search'
      - 'to delete'
      - 'unused'
  
  #Used for configuring what constitutes as a 'bookable item' - location based...
  bookable_item:
    loan_type: '24HR'
    location:
      - 'High Demand 1st Floor'

  # Location prefixes for holdings items (checks will be made for items availability at locations independently) 
  requestable_locations:
    - 'bjl'
    - 'kdl'


test:
  contact_form_email: r.j.garbutt@hull.ac.uk
  contact_form_bcc:
    - r.j.garbutt@hull.ac.uk

  #catalog address/port used for Z39.50 interface for holdings
  catalogue_server_address: libsys.lib.hull.ac.uk
  catalogue_server_port: 210

  #Z39.50 connection pool configurations
  #5 appears to be an optimal poolsize
  z39_connection_pool_size: 5
  z39_connection_timeout: 5

  #Library Catalogue OPAC address
  catalogue_opac_address: library.hull.ac.uk

  # Intersite transfer url
  intersite_transfer_url: http://www2.hull.ac.uk/lli/library-services/books/intersite.aspx

  #syndetics services for book covers and table of contents
  syndetics_client_code: dev

  # Used for building the link structure for the York 
  york_link_desc: 'This item in University of York Library'
  york_link_url: 'http://yorsearch.york.ac.uk/primo_library/libweb/action/dlSearch.do?institution=44YORK&vid=44YORK&query=any,contains,'

  # twitter widget data_id
  twitter_widget_data_id:  

  #configurations for addthis tool - See http://support.addthis.com/customer/portal/articles/381244-destinations-services
  addthis_services_compact: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket'
  addthis_services_expanded: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket,favorites'
  addthis_services_exclude: 'gmail,email'

  #Do not retrieve holdings for these formats
  holdings:
    ignore:
      - 'E-Book'
      - 'E-Journal'
      - 'Electronic resource'
      - 'Unknown'

   #status from holding records
  record_status:
    available:
      - 'ask at dept'
      - 'ask at hdc'   
      - 'available'
      - 'beingprocessed'
      - 'binding office'
      - 'donation'
      - 'due'
      - 'in repair'
      - 'in transit'
      - 'just catalogued'
      - 'on holdshelf'
      - 'requested'
      - 'returned today'
      - 'to collect'  
    not_available:
      - 'at bindery'
      - 'billed'
      - 'clms retd'
      - 'damaged copy'
      - 'disk missing'
      - 'intersite'
      - 'librar/office'
      - 'lib use only'
      - 'lost and paid'
      - 'lost in lib'
      - 'lost o/o/p'
      - 'missing'
      - 'not available'
      - 'on search'
      - 'to delete'
      - 'unused'

  #Used for configuring what constitutes as a 'bookable item' - location based...
  bookable_item:
    loan_type: '24HR'
    location:
      - 'High Demand 1st Floor'

  # Location prefixes for holdings items (checks will be made for items availability at locations independently) 
  requestable_locations:
    - 'bjl'
    - 'kdl'

production:
  contact_form_email: r.j.garbutt@hull.ac.uk
  contact_form_bcc:
    - r.j.garbutt@hull.ac.uk

  #catalog address/port used for Z39.50 interface for holdings
  catalogue_server_address: libsys.lib.hull.ac.uk
  catalogue_server_port: 210

  #Z39.50 connection pool configurations
  #5 appears to be an optimal poolsize
  z39_connection_pool_size: 5
  z39_connection_timeout: 5
  
  #Library Catalogue OPAC address
  catalogue_opac_address: library.hull.ac.uk

  # Intersite transfer url
  intersite_transfer_url: http://www2.hull.ac.uk/lli/library-services/books/intersite.aspx

  #syndetics services for book covers and table of contents
  syndetics_client_code: 

  # Used for building the link structure for the York 
  york_link_desc: 'This item in University of York Library'
  york_link_url: 'http://yorsearch.york.ac.uk/primo_library/libweb/action/dlSearch.do?institution=44YORK&vid=44YORK&query=any,contains,'

  # twitter widget data_id
  twitter_widget_data_id:  

  #configurations for addthis tool - See http://support.addthis.com/customer/portal/articles/381244-destinations-services
  addthis_services_compact: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket'
  addthis_services_expanded: 'twitter,facebook,google_plusone,google_plusone_share,pinterest,stumbleupon,delicious,digg,blogger,tumblr,pocket,favorites'
  addthis_services_exclude: 'gmail,email'

  #Do not retrieve holdings for these formats
  holdings:
    ignore:
      - 'E-Book'
      - 'E-Journal'
      - 'Electronic resource'
      - 'Unknown'

   #status from holding records
  record_status:
    available:
      - 'ask at dept'
      - 'ask at hdc'   
      - 'available'
      - 'beingprocessed'
      - 'binding office'
      - 'donation'
      - 'due'
      - 'in repair'
      - 'in transit'
      - 'just catalogued'
      - 'on holdshelf'
      - 'requested'
      - 'returned today'
      - 'to collect'  
    not_available:
      - 'at bindery'
      - 'billed'
      - 'clms retd'
      - 'damaged copy'
      - 'disk missing'
      - 'intersite'
      - 'librar/office'
      - 'lib use only'
      - 'lost and paid'
      - 'lost in lib'
      - 'lost o/o/p'
      - 'missing'
      - 'not available'
      - 'on search'
      - 'to delete'
      - 'unused'

  #Used for configuring what constitutes as a 'bookable item' - location based...
  bookable_item:
    loan_type: '24HR'
    location:
      - 'High Demand 1st Floor'

  # Location prefixes for holdings items (checks will be made for items availability at locations independently) 
  requestable_locations:
    - 'bjl'
    - 'kdl'
